import { Inter } from "next/font/google";
import "./globals.css";
import Appbar from "./component/Appbar";
import SignIn from "./component/SignIn";
import Box from '@mui/material/Box';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Box sx={{
          maxWidth: '80%',
          mx: 'auto',
          '@media (max-width: 600px)': {
            maxWidth: '100%',
          },
          p:0
        }}>
          <Appbar />
          {children}
        </Box>
        </body>
    </html>
  );
}
